name: 가상화폐 시세 조회

on:
  schedule:
    - cron: '0 13,16,20 * * *'
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set up JDK 17
        uses: actions/setup-java@v2
        with:
          java-version: '17'
          distribution: 'adopt'
      - name: Grant execute permission for gradlew
        run: chmod +x gradlew
      - name: Build with Gradle
        run: ./gradlew clean :build -x test
      - name: Run Batch Job
        run: java -jar -Dspring.batch.job.name=tickerSlackJob ./out/artifacts/cryptoautomation_jar/cryptoautomation.jar market=KRW-BTC

